In [2]:
import tensorflow as tf
from tqdm import tqdm
import keras
from keras.models import load_model, Sequential,Model
from keras.layers import Dense, Flatten, Softmax, Input, Reshape,Lambda,\
    Conv2D, MaxPool2D, Dropout,Concatenate,Embedding,BatchNormalization
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import cv2
import re
import numpy as np
import os
import time
import json
from inception_v3 import  InceptionV3,preprocess_input
from tqdm import tqdm, trange
import math
from utils import batch_generator
from NIC import model,greedy_inference_model,image_dense_lstm,text_emb_lstm
from pickle import dump, load

Using TensorFlow backend.


In [3]:
fp3= "data/captions_train2014.json"
with open(fp3,'r') as f3:
    mscoco_data= json.load(f3)
    





In [4]:
fp4= "sentence_dict2.json"
with open(fp4,"r") as f4 :
    sentiment_dict= json.load(f4)
    





In [5]:
def load_image(image_path):
    img= cv2.imread(image_path)
    img= cv2.resize(img,(299,299))
    img = (img*1.0)/255
    img = img-0.5 
    img = img*2
    return img




In [29]:
# top_k = vocab_size-1
# tokenizer = keras.preprocessing.text.Tokenizer(num_words=top_k,
#                                                   oov_token="<unk>",
#                                                   filters='!"#$%&()*+.,-/:;=?@[\]^_`{|}~ ')
# tokenizer.fit_on_texts(caption_train)
# tokenizer.word_index['<pad>'] = 0
# tokenizer.index_word[0] = '<pad>'
# 
# 
# train_seqs = tokenizer.texts_to_sequences(caption_train)
# cap_vector_train = keras.preprocessing.sequence.pad_sequences(train_seqs,dtype='int32', padding='post',truncating='post',maxlen=max_length+1,value=0)
# 
# print(train_seqs[0])
# print(cap_vector_train[0])


#

# num_examples=8000
# 
# image_name_train= img_name_vector[:num_examples]
# senti_train= senti_score[:num_examples]
# caption_train= train_caption[:num_examples]
# print(caption_train[0])


In [6]:
fp2="data/senticap_dataset.json"

with open(fp2,'r') as f2:
    senticap_data= json.load(f2)
senticap_list=[]
senticap_list_raw=[]
l=0
for img_obj in senticap_data['images']:
    # if (l>20):
    #     break
    # l+=1
    img_name= img_obj['filename']
    for sent in img_obj['sentences']:
        sentiment= sent['sentiment']
        raw= sent['raw'].lower()
        w0= raw.rstrip()
        w0 = [x.replace(".", "") for x in w0]
        w0= [x.replace(",","") for x in w0]
        w0= [x.replace("'","") for x in w0]
        w0= [x.replace("?","") for x in w0]
        w0="".join(w0)
        senticap_list.append((img_name,sentiment,w0))
        senticap_list_raw.append((img_name,w0))
        
        
        

In [7]:
"""read from output of nlp treebank"""

fname="new_out.txt"
i=0
l1=10000
senti_score=[]
senti_avg=[]
error=0
senti_var=[]
train_caption=[]
senti_cap_dict={}
with open(fname) as f1:
    while(i<l1):
        w1= f1.readline().strip()
        if not w1:
            break
        w2= f1.readline().strip()
        w1 = [x.replace(".", "") for x in w1]
        w1= [x.replace(",","") for x in w1]
        w1= [x.replace("'","") for x in w1]
        w1= [x.replace("?","") for x in w1]
        w1= "".join(x for x in w1)
        w1= w1.rstrip()
        w1= "".join(x for x in w1)

        if w2.islower():
            w1=w2
            w2=f1.readline().strip()
        a= 0
        if w2=="Negative":
            a= -1
        elif w2=="Positive":
            a= 1
        elif w2=="Very negative":
            a= -1
        elif w2=="Very positive":
            a= 1
        elif w2=="Neutral":
            a= 0
        else:
            a=0
            error+=1
            print(w2)
        senti_score.append(a)
        train_caption.append(w1)
        senti_cap_dict[w1]=a
        i+=1
# print(senti_score[0:500] )
print(len(train_caption),"train-cap_length")
print(len(senti_score),"train-senti_score")


" .
8861 train-cap_length
8861 train-senti_score


In [8]:
PATH_DIR= '/home/yiyang/project/caption/caption'
PATH= PATH_DIR+'/data/val2014/'
image_vec=[]
sentiment_vec=[]
caption_vec=[]

for item in senticap_list:
    img= item[0]
    if item[1]==1:
        senti=1
    elif item[1]==0:
        senti=-1
    else:
        senti=0

    caption= item[2]
    # print(caption+"#")
    if caption in senti_cap_dict.keys():
        new_senti= senti_cap_dict[caption]
    else:
        new_senti= 0
    img= PATH + img 
    caption= '<start> ' + caption + ' <end>'
    image_vec.append(img)
    sentiment_vec.append(new_senti)
    caption_vec.append(caption)
    
    

In [9]:
units= 512
embedding_size=511
BATCH_SIZE=80
vocab_size=4500
max_length=20
num_examples=8861

In [10]:
image_name_train= image_vec[:num_examples]
senti_train= sentiment_vec[:num_examples]
caption_train= caption_vec[:num_examples]


In [11]:
print(len(image_name_train))

8848


In [20]:
# input_imgs = []
#     # start=0
#     # print(start,'start')
# for j in trange(len(image_name_train)):
#     img = load_image(image_name_train[ j])
#     img = (img*1.0)/255
#     img = img-0.5 
#     img = img*2
#     input_imgs.append(img)


  0%|          | 0/8848 [00:00<?, ?it/s]

  0%|          | 12/8848 [00:00<01:17, 113.61it/s]

  0%|          | 32/8848 [00:00<01:07, 130.10it/s]

  1%|          | 53/8848 [00:00<01:00, 145.31it/s]

  1%|          | 66/8848 [00:00<01:03, 138.36it/s]

  1%|          | 83/8848 [00:00<01:00, 145.02it/s]

  1%|          | 102/8848 [00:00<00:56, 155.28it/s]

  1%|▏         | 117/8848 [00:00<00:58, 150.45it/s]

  2%|▏         | 133/8848 [00:00<00:57, 151.68it/s]

  2%|▏         | 153/8848 [00:00<00:53, 162.28it/s]

  2%|▏         | 170/8848 [00:01<00:55, 157.55it/s]

  2%|▏         | 186/8848 [00:01<00:56, 154.49it/s]

  2%|▏         | 204/8848 [00:01<00:53, 160.69it/s]

  2%|▏         | 221/8848 [00:01<00:54, 157.31it/s]

  3%|▎         | 238/8848 [00:01<00:54, 158.48it/s]

  3%|▎         | 255/8848 [00:01<00:53, 159.15it/s]

  3%|▎         | 271/8848 [00:01<00:54, 158.82it/s]

  3%|▎         | 288/8848 [00:01<00:53, 161.34it/s]

  3%|▎         | 305/8848 [00:01<00:54, 156.05it/s]

  4%|▎         | 324/8848 [00:02<00:52, 163.14it/s]

  4%|▍         | 345/8848 [00:02<00:49, 172.96it/s]

  4%|▍         | 366/8848 [00:02<00:46, 181.45it/s]

  4%|▍         | 385/8848 [00:02<00:49, 171.23it/s]

  5%|▍         | 403/8848 [00:02<00:50, 166.40it/s]

  5%|▍         | 424/8848 [00:02<00:47, 175.73it/s]

  5%|▌         | 444/8848 [00:02<00:46, 182.24it/s]

  5%|▌         | 468/8848 [00:02<00:42, 195.50it/s]

  6%|▌         | 489/8848 [00:02<00:42, 195.22it/s]

  6%|▌         | 509/8848 [00:02<00:42, 195.66it/s]

  6%|▌         | 529/8848 [00:03<00:42, 196.36it/s]

  6%|▋         | 554/8848 [00:03<00:39, 209.24it/s]

  7%|▋         | 576/8848 [00:03<00:40, 202.27it/s]

  7%|▋         | 597/8848 [00:03<00:42, 195.95it/s]

  7%|▋         | 619/8848 [00:03<00:41, 200.27it/s]

  7%|▋         | 642/8848 [00:03<00:39, 207.58it/s]

  7%|▋         | 663/8848 [00:03<00:39, 204.97it/s]

  8%|▊         | 686/8848 [00:03<00:38, 209.28it/s]

  8%|▊         | 708/8848 [00:03<00:40, 198.54it/s]

  8%|▊         | 729/8848 [00:04<00:40, 199.34it/s]

  8%|▊         | 752/8848 [00:04<00:39, 207.47it/s]

  9%|▊         | 773/8848 [00:04<00:40, 200.63it/s]

  9%|▉         | 794/8848 [00:04<00:39, 203.24it/s]

  9%|▉         | 815/8848 [00:04<00:39, 201.55it/s]

  9%|▉         | 836/8848 [00:04<00:41, 194.09it/s]

 10%|▉         | 861/8848 [00:04<00:38, 206.07it/s]

 10%|▉         | 882/8848 [00:04<00:39, 202.58it/s]

 10%|█         | 907/8848 [00:04<00:37, 212.84it/s]

 11%|█         | 930/8848 [00:05<00:36, 214.47it/s]

 11%|█         | 952/8848 [00:05<00:37, 209.37it/s]

 11%|█         | 974/8848 [00:05<00:37, 210.26it/s]

 11%|█▏        | 996/8848 [00:05<00:37, 211.77it/s]

 12%|█▏        | 1018/8848 [00:05<00:38, 204.11it/s]

 12%|█▏        | 1045/8848 [00:05<00:35, 218.90it/s]

 12%|█▏        | 1068/8848 [00:05<00:37, 207.50it/s]

 12%|█▏        | 1090/8848 [00:05<00:37, 208.94it/s]

 13%|█▎        | 1112/8848 [00:05<00:37, 206.81it/s]

 13%|█▎        | 1134/8848 [00:05<00:37, 208.02it/s]

 13%|█▎        | 1156/8848 [00:06<00:36, 209.77it/s]

 13%|█▎        | 1178/8848 [00:06<00:36, 208.66it/s]

 14%|█▎        | 1202/8848 [00:06<00:35, 217.06it/s]

 14%|█▍        | 1224/8848 [00:06<00:36, 206.87it/s]

 14%|█▍        | 1245/8848 [00:06<00:38, 199.51it/s]

 14%|█▍        | 1269/8848 [00:06<00:36, 209.27it/s]

 15%|█▍        | 1291/8848 [00:06<00:37, 202.87it/s]

 15%|█▍        | 1312/8848 [00:06<00:39, 189.23it/s]

 15%|█▌        | 1332/8848 [00:06<00:39, 191.17it/s]

 15%|█▌        | 1352/8848 [00:07<00:38, 193.19it/s]

 16%|█▌        | 1372/8848 [00:07<00:38, 194.49it/s]

 16%|█▌        | 1396/8848 [00:07<00:36, 204.47it/s]

 16%|█▌        | 1418/8848 [00:07<00:35, 207.78it/s]

 16%|█▋        | 1440/8848 [00:07<00:35, 210.65it/s]

 17%|█▋        | 1462/8848 [00:07<00:35, 209.34it/s]

 17%|█▋        | 1484/8848 [00:07<00:35, 206.36it/s]

 17%|█▋        | 1505/8848 [00:07<00:36, 199.40it/s]

 17%|█▋        | 1526/8848 [00:07<00:36, 198.82it/s]

 17%|█▋        | 1547/8848 [00:08<00:36, 201.28it/s]

 18%|█▊        | 1568/8848 [00:08<00:37, 196.47it/s]

 18%|█▊        | 1591/8848 [00:08<00:35, 203.73it/s]

 18%|█▊        | 1613/8848 [00:08<00:34, 206.92it/s]

 18%|█▊        | 1636/8848 [00:08<00:34, 211.04it/s]

 19%|█▊        | 1658/8848 [00:08<00:35, 205.38it/s]

 19%|█▉        | 1679/8848 [00:08<00:34, 205.61it/s]

 19%|█▉        | 1700/8848 [00:08<00:36, 197.44it/s]

 19%|█▉        | 1720/8848 [00:08<00:37, 191.46it/s]

 20%|█▉        | 1740/8848 [00:09<00:38, 186.76it/s]

 20%|█▉        | 1760/8848 [00:09<00:37, 187.89it/s]

 20%|██        | 1780/8848 [00:09<00:37, 190.84it/s]

 20%|██        | 1800/8848 [00:09<00:37, 190.07it/s]

 21%|██        | 1822/8848 [00:09<00:35, 195.44it/s]

 21%|██        | 1842/8848 [00:09<00:37, 189.29it/s]

 21%|██        | 1865/8848 [00:09<00:35, 198.62it/s]

 21%|██▏       | 1887/8848 [00:09<00:34, 201.65it/s]

 22%|██▏       | 1908/8848 [00:09<00:34, 200.84it/s]

 22%|██▏       | 1930/8848 [00:09<00:33, 204.31it/s]

 22%|██▏       | 1951/8848 [00:10<00:33, 204.51it/s]

 22%|██▏       | 1972/8848 [00:10<00:33, 204.39it/s]

 23%|██▎       | 1995/8848 [00:10<00:32, 208.83it/s]

 23%|██▎       | 2016/8848 [00:10<00:33, 203.71it/s]

 23%|██▎       | 2037/8848 [00:10<00:33, 203.17it/s]

 23%|██▎       | 2058/8848 [00:10<00:33, 202.21it/s]

 23%|██▎       | 2079/8848 [00:10<00:33, 201.47it/s]

 24%|██▎       | 2100/8848 [00:10<00:33, 201.17it/s]

 24%|██▍       | 2122/8848 [00:10<00:32, 204.84it/s]

 24%|██▍       | 2144/8848 [00:10<00:32, 206.37it/s]

 24%|██▍       | 2166/8848 [00:11<00:32, 208.07it/s]

 25%|██▍       | 2190/8848 [00:11<00:30, 215.39it/s]

 25%|██▌       | 2212/8848 [00:11<00:31, 209.20it/s]

 25%|██▌       | 2237/8848 [00:11<00:30, 218.56it/s]

 26%|██▌       | 2260/8848 [00:11<00:31, 212.10it/s]

 26%|██▌       | 2282/8848 [00:11<00:32, 203.67it/s]

 26%|██▌       | 2303/8848 [00:11<00:33, 195.90it/s]

 26%|██▋       | 2328/8848 [00:11<00:31, 208.50it/s]

 27%|██▋       | 2350/8848 [00:11<00:31, 209.31it/s]

 27%|██▋       | 2372/8848 [00:12<00:31, 202.39it/s]

 27%|██▋       | 2393/8848 [00:12<00:32, 198.78it/s]

 27%|██▋       | 2414/8848 [00:12<00:32, 200.93it/s]

 28%|██▊       | 2435/8848 [00:12<00:32, 199.19it/s]

 28%|██▊       | 2456/8848 [00:12<00:32, 198.60it/s]

 28%|██▊       | 2480/8848 [00:12<00:30, 206.76it/s]

 28%|██▊       | 2501/8848 [00:12<00:31, 203.95it/s]

 29%|██▊       | 2523/8848 [00:12<00:30, 208.31it/s]

 29%|██▉       | 2544/8848 [00:12<00:32, 191.88it/s]

 29%|██▉       | 2572/8848 [00:13<00:29, 209.84it/s]

 29%|██▉       | 2594/8848 [00:13<00:29, 211.93it/s]

 30%|██▉       | 2616/8848 [00:13<00:29, 208.79it/s]

 30%|██▉       | 2640/8848 [00:13<00:28, 215.04it/s]

 30%|███       | 2663/8848 [00:13<00:28, 217.45it/s]

 30%|███       | 2686/8848 [00:13<00:28, 218.22it/s]

 31%|███       | 2708/8848 [00:13<00:29, 208.77it/s]

 31%|███       | 2730/8848 [00:13<00:29, 206.88it/s]

 31%|███       | 2751/8848 [00:13<00:29, 204.71it/s]

 31%|███▏      | 2774/8848 [00:14<00:28, 211.48it/s]

 32%|███▏      | 2796/8848 [00:14<00:29, 208.30it/s]

 32%|███▏      | 2817/8848 [00:14<00:29, 202.44it/s]

 32%|███▏      | 2838/8848 [00:14<00:29, 203.41it/s]

 32%|███▏      | 2859/8848 [00:14<00:29, 200.00it/s]

 33%|███▎      | 2880/8848 [00:14<00:30, 196.48it/s]

 33%|███▎      | 2906/8848 [00:14<00:28, 211.20it/s]

 33%|███▎      | 2928/8848 [00:14<00:28, 206.42it/s]

 33%|███▎      | 2949/8848 [00:14<00:28, 203.55it/s]

 34%|███▎      | 2970/8848 [00:14<00:28, 204.86it/s]

 34%|███▍      | 2991/8848 [00:15<00:29, 201.86it/s]

 34%|███▍      | 3012/8848 [00:15<00:28, 202.97it/s]

 34%|███▍      | 3033/8848 [00:15<00:28, 202.74it/s]

 35%|███▍      | 3054/8848 [00:15<00:28, 202.75it/s]

 35%|███▍      | 3076/8848 [00:15<00:28, 205.33it/s]

 35%|███▌      | 3098/8848 [00:15<00:27, 206.91it/s]

 35%|███▌      | 3119/8848 [00:15<00:29, 196.94it/s]

 35%|███▌      | 3139/8848 [00:15<00:29, 195.49it/s]

 36%|███▌      | 3159/8848 [00:15<00:29, 192.57it/s]

 36%|███▌      | 3180/8848 [00:16<00:29, 195.00it/s]

 36%|███▌      | 3200/8848 [00:16<00:29, 192.92it/s]

 36%|███▋      | 3224/8848 [00:16<00:27, 204.14it/s]

 37%|███▋      | 3245/8848 [00:16<00:27, 202.22it/s]

 37%|███▋      | 3266/8848 [00:16<00:27, 202.27it/s]

 37%|███▋      | 3287/8848 [00:16<00:27, 200.52it/s]

 37%|███▋      | 3308/8848 [00:16<00:27, 202.01it/s]

 38%|███▊      | 3329/8848 [00:16<00:27, 203.03it/s]

 38%|███▊      | 3350/8848 [00:16<00:28, 193.78it/s]

 38%|███▊      | 3371/8848 [00:16<00:27, 197.14it/s]

 38%|███▊      | 3392/8848 [00:17<00:27, 199.13it/s]

 39%|███▊      | 3414/8848 [00:17<00:26, 203.67it/s]

 39%|███▉      | 3435/8848 [00:17<00:27, 194.93it/s]

 39%|███▉      | 3457/8848 [00:17<00:26, 200.27it/s]

 39%|███▉      | 3478/8848 [00:17<00:27, 194.03it/s]

 40%|███▉      | 3498/8848 [00:17<00:27, 193.32it/s]

 40%|███▉      | 3520/8848 [00:17<00:26, 200.17it/s]

 40%|████      | 3541/8848 [00:17<00:26, 202.30it/s]

 40%|████      | 3562/8848 [00:17<00:26, 200.32it/s]

 40%|████      | 3583/8848 [00:18<00:26, 195.79it/s]

 41%|████      | 3603/8848 [00:18<00:26, 194.38it/s]

 41%|████      | 3623/8848 [00:18<00:27, 192.92it/s]

 41%|████      | 3644/8848 [00:18<00:26, 197.42it/s]

 41%|████▏     | 3664/8848 [00:18<00:26, 196.16it/s]

 42%|████▏     | 3685/8848 [00:18<00:26, 197.67it/s]

 42%|████▏     | 3707/8848 [00:18<00:25, 203.07it/s]

 42%|████▏     | 3729/8848 [00:18<00:24, 205.06it/s]

 42%|████▏     | 3750/8848 [00:18<00:25, 203.91it/s]

 43%|████▎     | 3772/8848 [00:18<00:24, 207.86it/s]

 43%|████▎     | 3794/8848 [00:19<00:24, 210.15it/s]

 43%|████▎     | 3816/8848 [00:19<00:24, 203.88it/s]

 43%|████▎     | 3838/8848 [00:19<00:24, 205.62it/s]

 44%|████▎     | 3859/8848 [00:19<00:24, 206.84it/s]

 44%|████▍     | 3880/8848 [00:19<00:24, 203.29it/s]

 44%|████▍     | 3902/8848 [00:19<00:23, 207.69it/s]

 44%|████▍     | 3923/8848 [00:19<00:24, 204.29it/s]

 45%|████▍     | 3944/8848 [00:19<00:24, 200.92it/s]

 45%|████▍     | 3965/8848 [00:19<00:24, 199.91it/s]

 45%|████▌     | 3986/8848 [00:20<00:24, 197.67it/s]

 45%|████▌     | 4006/8848 [00:20<00:24, 194.10it/s]

 46%|████▌     | 4029/8848 [00:20<00:23, 201.34it/s]

 46%|████▌     | 4051/8848 [00:20<00:23, 205.56it/s]

 46%|████▌     | 4072/8848 [00:20<00:23, 203.35it/s]

 46%|████▋     | 4094/8848 [00:20<00:23, 205.67it/s]

 47%|████▋     | 4116/8848 [00:20<00:22, 207.28it/s]

 47%|████▋     | 4137/8848 [00:20<00:23, 204.38it/s]

 47%|████▋     | 4158/8848 [00:20<00:22, 205.65it/s]

 47%|████▋     | 4179/8848 [00:20<00:22, 205.39it/s]

 47%|████▋     | 4200/8848 [00:21<00:22, 205.68it/s]

 48%|████▊     | 4221/8848 [00:21<00:22, 205.59it/s]

 48%|████▊     | 4242/8848 [00:21<00:23, 199.23it/s]

 48%|████▊     | 4262/8848 [00:21<00:23, 197.84it/s]

 48%|████▊     | 4282/8848 [00:21<00:23, 197.54it/s]

 49%|████▊     | 4303/8848 [00:21<00:22, 199.16it/s]

 49%|████▉     | 4324/8848 [00:21<00:22, 202.12it/s]

 49%|████▉     | 4345/8848 [00:21<00:22, 204.39it/s]

 49%|████▉     | 4366/8848 [00:21<00:22, 203.22it/s]

 50%|████▉     | 4387/8848 [00:22<00:21, 205.05it/s]

 50%|████▉     | 4408/8848 [00:22<00:22, 200.21it/s]

 50%|█████     | 4429/8848 [00:22<00:22, 200.23it/s]

 50%|█████     | 4452/8848 [00:22<00:21, 206.92it/s]

 51%|█████     | 4473/8848 [00:22<00:21, 202.27it/s]

 51%|█████     | 4495/8848 [00:22<00:21, 207.03it/s]

 51%|█████     | 4516/8848 [00:22<00:21, 199.86it/s]

 51%|█████▏    | 4537/8848 [00:22<00:21, 197.75it/s]

 52%|█████▏    | 4557/8848 [00:22<00:22, 191.26it/s]

 52%|█████▏    | 4577/8848 [00:22<00:22, 192.65it/s]

 52%|█████▏    | 4600/8848 [00:23<00:21, 200.84it/s]

 52%|█████▏    | 4621/8848 [00:23<00:20, 203.09it/s]

 52%|█████▏    | 4643/8848 [00:23<00:20, 206.75it/s]

 53%|█████▎    | 4664/8848 [00:23<00:20, 200.02it/s]

 53%|█████▎    | 4685/8848 [00:23<00:20, 201.10it/s]

 53%|█████▎    | 4706/8848 [00:23<00:21, 196.74it/s]

 53%|█████▎    | 4728/8848 [00:23<00:20, 200.75it/s]

 54%|█████▎    | 4749/8848 [00:23<00:20, 195.86it/s]

 54%|█████▍    | 4769/8848 [00:23<00:21, 194.07it/s]

 54%|█████▍    | 4791/8848 [00:24<00:20, 199.17it/s]

 54%|█████▍    | 4811/8848 [00:24<00:20, 198.56it/s]

 55%|█████▍    | 4835/8848 [00:24<00:19, 207.64it/s]

 55%|█████▍    | 4857/8848 [00:24<00:19, 209.47it/s]

 55%|█████▌    | 4880/8848 [00:24<00:18, 212.84it/s]

 55%|█████▌    | 4902/8848 [00:24<00:19, 201.65it/s]

 56%|█████▌    | 4923/8848 [00:24<00:19, 199.94it/s]

 56%|█████▌    | 4944/8848 [00:24<00:19, 202.67it/s]

 56%|█████▌    | 4965/8848 [00:24<00:19, 196.63it/s]

 56%|█████▋    | 4988/8848 [00:24<00:18, 204.46it/s]

 57%|█████▋    | 5009/8848 [00:25<00:19, 201.92it/s]

 57%|█████▋    | 5030/8848 [00:25<00:18, 201.62it/s]

 57%|█████▋    | 5051/8848 [00:25<00:18, 203.40it/s]

 57%|█████▋    | 5073/8848 [00:25<00:18, 205.76it/s]

 58%|█████▊    | 5095/8848 [00:25<00:18, 207.46it/s]

 58%|█████▊    | 5117/8848 [00:25<00:17, 209.12it/s]

 58%|█████▊    | 5138/8848 [00:25<00:18, 204.31it/s]

 58%|█████▊    | 5163/8848 [00:25<00:17, 213.63it/s]

 59%|█████▊    | 5185/8848 [00:25<00:17, 210.54it/s]

 59%|█████▉    | 5207/8848 [00:26<00:17, 206.12it/s]

 59%|█████▉    | 5228/8848 [00:26<00:17, 202.71it/s]

 59%|█████▉    | 5249/8848 [00:26<00:18, 198.93it/s]

 60%|█████▉    | 5269/8848 [00:26<00:18, 194.20it/s]

 60%|█████▉    | 5289/8848 [00:26<00:18, 195.24it/s]

 60%|██████    | 5309/8848 [00:26<00:18, 192.91it/s]

 60%|██████    | 5329/8848 [00:26<00:18, 194.78it/s]

 60%|██████    | 5349/8848 [00:26<00:18, 190.68it/s]

 61%|██████    | 5369/8848 [00:26<00:18, 190.46it/s]

 61%|██████    | 5392/8848 [00:27<00:17, 200.14it/s]

 61%|██████    | 5413/8848 [00:27<00:17, 197.67it/s]

 61%|██████▏   | 5433/8848 [00:27<00:17, 195.32it/s]

 62%|██████▏   | 5453/8848 [00:27<00:17, 196.14it/s]

 62%|██████▏   | 5477/8848 [00:27<00:16, 205.38it/s]

 62%|██████▏   | 5498/8848 [00:27<00:17, 193.00it/s]

 62%|██████▏   | 5521/8848 [00:27<00:16, 201.65it/s]

 63%|██████▎   | 5544/8848 [00:27<00:15, 209.09it/s]

 63%|██████▎   | 5568/8848 [00:27<00:15, 215.47it/s]

 63%|██████▎   | 5590/8848 [00:27<00:15, 206.06it/s]

 63%|██████▎   | 5612/8848 [00:28<00:15, 209.51it/s]

 64%|██████▎   | 5634/8848 [00:28<00:15, 206.67it/s]

 64%|██████▍   | 5655/8848 [00:28<00:15, 204.65it/s]

 64%|██████▍   | 5678/8848 [00:28<00:15, 209.25it/s]

 64%|██████▍   | 5700/8848 [00:28<00:15, 203.56it/s]

 65%|██████▍   | 5721/8848 [00:28<00:15, 197.88it/s]

 65%|██████▍   | 5745/8848 [00:28<00:15, 206.07it/s]

 65%|██████▌   | 5766/8848 [00:28<00:15, 195.61it/s]

 65%|██████▌   | 5788/8848 [00:28<00:15, 200.44it/s]

 66%|██████▌   | 5810/8848 [00:29<00:14, 204.43it/s]

 66%|██████▌   | 5831/8848 [00:29<00:15, 193.82it/s]

 66%|██████▌   | 5851/8848 [00:29<00:15, 191.43it/s]

 66%|██████▋   | 5872/8848 [00:29<00:15, 194.68it/s]

 67%|██████▋   | 5893/8848 [00:29<00:14, 198.00it/s]

 67%|██████▋   | 5915/8848 [00:29<00:14, 202.80it/s]

 67%|██████▋   | 5936/8848 [00:29<00:14, 199.76it/s]

 67%|██████▋   | 5957/8848 [00:29<00:15, 185.75it/s]

 68%|██████▊   | 5979/8848 [00:29<00:14, 192.65it/s]

 68%|██████▊   | 5999/8848 [00:30<00:15, 188.73it/s]

 68%|██████▊   | 6019/8848 [00:30<00:14, 190.35it/s]

 68%|██████▊   | 6039/8848 [00:30<00:14, 192.78it/s]

 69%|██████▊   | 6065/8848 [00:30<00:13, 207.83it/s]

 69%|██████▉   | 6087/8848 [00:30<00:13, 208.28it/s]

 69%|██████▉   | 6109/8848 [00:30<00:13, 208.76it/s]

 69%|██████▉   | 6131/8848 [00:30<00:12, 211.62it/s]

 70%|██████▉   | 6153/8848 [00:30<00:13, 203.08it/s]

 70%|██████▉   | 6174/8848 [00:30<00:13, 197.69it/s]

 70%|███████   | 6194/8848 [00:30<00:13, 197.90it/s]

 70%|███████   | 6216/8848 [00:31<00:13, 202.10it/s]

 71%|███████   | 6239/8848 [00:31<00:12, 208.96it/s]

 71%|███████   | 6261/8848 [00:31<00:12, 205.31it/s]

 71%|███████   | 6282/8848 [00:31<00:12, 200.71it/s]

 71%|███████   | 6303/8848 [00:31<00:12, 198.85it/s]

 71%|███████▏  | 6325/8848 [00:31<00:12, 202.50it/s]

 72%|███████▏  | 6346/8848 [00:31<00:12, 196.35it/s]

 72%|███████▏  | 6366/8848 [00:31<00:12, 192.71it/s]

 72%|███████▏  | 6386/8848 [00:31<00:13, 188.54it/s]

 72%|███████▏  | 6405/8848 [00:32<00:13, 183.60it/s]

 73%|███████▎  | 6424/8848 [00:32<00:13, 184.25it/s]

 73%|███████▎  | 6446/8848 [00:32<00:12, 193.17it/s]

 73%|███████▎  | 6469/8848 [00:32<00:11, 199.77it/s]

 73%|███████▎  | 6491/8848 [00:32<00:11, 205.16it/s]

 74%|███████▎  | 6512/8848 [00:32<00:11, 205.45it/s]

 74%|███████▍  | 6533/8848 [00:32<00:11, 193.73it/s]

 74%|███████▍  | 6553/8848 [00:32<00:12, 187.19it/s]

 74%|███████▍  | 6578/8848 [00:32<00:11, 200.84it/s]

 75%|███████▍  | 6599/8848 [00:33<00:11, 195.49it/s]

 75%|███████▍  | 6619/8848 [00:33<00:11, 194.90it/s]

 75%|███████▌  | 6641/8848 [00:33<00:10, 200.86it/s]

 75%|███████▌  | 6663/8848 [00:33<00:10, 205.10it/s]

 76%|███████▌  | 6685/8848 [00:33<00:10, 208.20it/s]

 76%|███████▌  | 6708/8848 [00:33<00:10, 210.11it/s]

 76%|███████▌  | 6730/8848 [00:33<00:10, 200.84it/s]

 76%|███████▋  | 6751/8848 [00:33<00:10, 198.40it/s]

 77%|███████▋  | 6772/8848 [00:33<00:10, 198.73it/s]

 77%|███████▋  | 6792/8848 [00:33<00:10, 197.59it/s]

 77%|███████▋  | 6817/8848 [00:34<00:09, 208.38it/s]

 77%|███████▋  | 6839/8848 [00:34<00:09, 202.81it/s]

 78%|███████▊  | 6860/8848 [00:34<00:10, 197.36it/s]

 78%|███████▊  | 6881/8848 [00:34<00:09, 199.16it/s]

 78%|███████▊  | 6902/8848 [00:34<00:09, 199.23it/s]

 78%|███████▊  | 6923/8848 [00:34<00:09, 200.53it/s]

 78%|███████▊  | 6944/8848 [00:34<00:09, 200.40it/s]

 79%|███████▊  | 6965/8848 [00:34<00:09, 201.55it/s]

 79%|███████▉  | 6986/8848 [00:34<00:09, 196.30it/s]

 79%|███████▉  | 7006/8848 [00:35<00:09, 193.84it/s]

 79%|███████▉  | 7027/8848 [00:35<00:09, 197.54it/s]

 80%|███████▉  | 7047/8848 [00:35<00:09, 193.83it/s]

 80%|███████▉  | 7067/8848 [00:35<00:09, 191.11it/s]

 80%|████████  | 7089/8848 [00:35<00:08, 196.52it/s]

 80%|████████  | 7110/8848 [00:35<00:08, 199.06it/s]

 81%|████████  | 7134/8848 [00:35<00:08, 208.98it/s]

 81%|████████  | 7156/8848 [00:35<00:08, 206.22it/s]

 81%|████████  | 7178/8848 [00:35<00:08, 208.34it/s]

 81%|████████▏ | 7200/8848 [00:36<00:07, 208.61it/s]

 82%|████████▏ | 7221/8848 [00:36<00:08, 202.84it/s]

 82%|████████▏ | 7243/8848 [00:36<00:07, 206.39it/s]

 82%|████████▏ | 7264/8848 [00:36<00:07, 206.08it/s]

 82%|████████▏ | 7286/8848 [00:36<00:07, 208.62it/s]

 83%|████████▎ | 7307/8848 [00:36<00:07, 201.63it/s]

 83%|████████▎ | 7329/8848 [00:36<00:07, 204.76it/s]

 83%|████████▎ | 7353/8848 [00:36<00:06, 213.68it/s]

 83%|████████▎ | 7375/8848 [00:36<00:06, 213.84it/s]

 84%|████████▎ | 7397/8848 [00:36<00:06, 213.30it/s]

 84%|████████▍ | 7419/8848 [00:37<00:06, 207.85it/s]

 84%|████████▍ | 7440/8848 [00:37<00:07, 197.02it/s]

 84%|████████▍ | 7464/8848 [00:37<00:06, 206.92it/s]

 85%|████████▍ | 7487/8848 [00:37<00:06, 211.76it/s]

 85%|████████▍ | 7509/8848 [00:37<00:06, 213.16it/s]

 85%|████████▌ | 7531/8848 [00:37<00:06, 205.92it/s]

 85%|████████▌ | 7552/8848 [00:37<00:06, 199.93it/s]

 86%|████████▌ | 7573/8848 [00:37<00:06, 193.60it/s]

 86%|████████▌ | 7594/8848 [00:37<00:06, 195.78it/s]

 86%|████████▌ | 7614/8848 [00:38<00:06, 194.45it/s]

 86%|████████▋ | 7635/8848 [00:38<00:06, 197.99it/s]

 87%|████████▋ | 7657/8848 [00:38<00:05, 203.69it/s]

 87%|████████▋ | 7678/8848 [00:38<00:05, 202.59it/s]

 87%|████████▋ | 7699/8848 [00:38<00:05, 204.52it/s]

 87%|████████▋ | 7720/8848 [00:38<00:05, 192.61it/s]

 87%|████████▋ | 7741/8848 [00:38<00:05, 195.64it/s]

 88%|████████▊ | 7762/8848 [00:38<00:05, 197.00it/s]

 88%|████████▊ | 7782/8848 [00:38<00:05, 196.80it/s]

 88%|████████▊ | 7802/8848 [00:38<00:05, 193.26it/s]

 88%|████████▊ | 7823/8848 [00:39<00:05, 196.38it/s]

 89%|████████▊ | 7844/8848 [00:39<00:05, 199.60it/s]

 89%|████████▉ | 7866/8848 [00:39<00:04, 203.01it/s]

 89%|████████▉ | 7887/8848 [00:39<00:04, 197.56it/s]

 89%|████████▉ | 7907/8848 [00:39<00:04, 193.31it/s]

 90%|████████▉ | 7927/8848 [00:39<00:04, 194.53it/s]

 90%|████████▉ | 7947/8848 [00:39<00:04, 194.62it/s]

 90%|█████████ | 7969/8848 [00:39<00:04, 199.25it/s]

 90%|█████████ | 7989/8848 [00:39<00:04, 197.36it/s]

 91%|█████████ | 8009/8848 [00:40<00:04, 197.23it/s]

 91%|█████████ | 8029/8848 [00:40<00:04, 193.54it/s]

 91%|█████████ | 8049/8848 [00:40<00:04, 195.31it/s]

 91%|█████████ | 8069/8848 [00:40<00:04, 194.07it/s]

 91%|█████████▏| 8089/8848 [00:40<00:03, 192.40it/s]

 92%|█████████▏| 8109/8848 [00:40<00:03, 192.46it/s]

 92%|█████████▏| 8130/8848 [00:40<00:03, 195.83it/s]

 92%|█████████▏| 8150/8848 [00:40<00:03, 193.63it/s]

 92%|█████████▏| 8170/8848 [00:40<00:03, 194.84it/s]

 93%|█████████▎| 8190/8848 [00:40<00:03, 195.40it/s]

 93%|█████████▎| 8212/8848 [00:41<00:03, 200.36it/s]

 93%|█████████▎| 8233/8848 [00:41<00:03, 191.25it/s]

 93%|█████████▎| 8253/8848 [00:41<00:03, 192.16it/s]

 94%|█████████▎| 8273/8848 [00:41<00:02, 192.63it/s]

 94%|█████████▍| 8296/8848 [00:41<00:02, 201.42it/s]

 94%|█████████▍| 8317/8848 [00:41<00:02, 200.65it/s]

 94%|█████████▍| 8338/8848 [00:41<00:02, 201.98it/s]

 94%|█████████▍| 8359/8848 [00:41<00:02, 198.02it/s]

 95%|█████████▍| 8379/8848 [00:41<00:02, 195.62it/s]

 95%|█████████▍| 8399/8848 [00:42<00:02, 196.46it/s]

 95%|█████████▌| 8420/8848 [00:42<00:02, 197.48it/s]

 95%|█████████▌| 8440/8848 [00:42<00:02, 190.37it/s]

 96%|█████████▌| 8462/8848 [00:42<00:01, 197.63it/s]

 96%|█████████▌| 8482/8848 [00:42<00:01, 193.76it/s]

 96%|█████████▌| 8505/8848 [00:42<00:01, 200.35it/s]

 96%|█████████▋| 8526/8848 [00:42<00:01, 195.15it/s]

 97%|█████████▋| 8546/8848 [00:42<00:01, 194.42it/s]

 97%|█████████▋| 8566/8848 [00:42<00:01, 192.18it/s]

 97%|█████████▋| 8588/8848 [00:42<00:01, 199.43it/s]

 97%|█████████▋| 8609/8848 [00:43<00:01, 197.52it/s]

 98%|█████████▊| 8631/8848 [00:43<00:01, 201.08it/s]

 98%|█████████▊| 8652/8848 [00:43<00:00, 200.78it/s]

 98%|█████████▊| 8673/8848 [00:43<00:00, 199.45it/s]

 98%|█████████▊| 8693/8848 [00:43<00:00, 198.83it/s]

 98%|█████████▊| 8713/8848 [00:43<00:00, 193.09it/s]

 99%|█████████▊| 8733/8848 [00:43<00:00, 194.87it/s]

 99%|█████████▉| 8754/8848 [00:43<00:00, 198.42it/s]

 99%|█████████▉| 8774/8848 [00:43<00:00, 197.24it/s]

 99%|█████████▉| 8794/8848 [00:44<00:00, 196.17it/s]

100%|█████████▉| 8815/8848 [00:44<00:00, 197.26it/s]

100%|█████████▉| 8835/8848 [00:44<00:00, 195.31it/s]

100%|██████████| 8848/8848 [00:44<00:00, 199.71it/s]

In [21]:
# print(input_imgs[0])

[[[-0.84313725 -0.81960784 -0.76470588]
  [-0.85882353 -0.83529412 -0.76470588]
  [-0.8745098  -0.84313725 -0.74117647]
  ...
  [-0.64705882 -0.76470588 -0.76470588]
  [-0.69411765 -0.81960784 -0.84313725]
  [-0.70196078 -0.81960784 -0.84313725]]

 [[-0.82745098 -0.81960784 -0.74901961]
  [-0.84313725 -0.82745098 -0.74901961]
  [-0.85098039 -0.81960784 -0.71764706]
  ...
  [-0.65490196 -0.76470588 -0.75686275]
  [-0.70196078 -0.83529412 -0.84313725]
  [-0.6627451  -0.79607843 -0.79607843]]

 [[-0.85098039 -0.83529412 -0.78823529]
  [-0.85882353 -0.83529412 -0.77254902]
  [-0.85882353 -0.81960784 -0.74901961]
  ...
  [-0.43529412 -0.60784314 -0.51372549]
  [-0.56078431 -0.74117647 -0.68627451]
  [-0.6        -0.76470588 -0.74117647]]

 ...

 [[-0.89803922 -0.90588235 -0.86666667]
  [-0.91372549 -0.89019608 -0.85098039]
  [-0.90588235 -0.89019608 -0.85882353]
  ...
  [-0.94509804 -0.94509804 -0.94509804]
  [-0.9372549  -0.9372549  -0.9372549 ]
  [-0.96078431 -0.96078431 -0.96078431]]

 [

In [22]:


base_model = InceptionV3(include_top=True, weights=None)
weights_path = 'data/image_net.h5'

base_model.load_weights(weights_path)


new_input = base_model.layers[0].input
hidden_layer = base_model.get_layer('avg_pool').output

image_model = Model(new_input, hidden_layer)
    

W1006 21:03:43.836706 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



W1006 21:03:43.848541 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W1006 21:03:43.851454 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W1006 21:03:43.862426 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



W1006 21:03:43.862847 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W1006 21:03:45.393569 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.



W1006 21:03:45.533812 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W1006 21:03:45.925158 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.



In [12]:
# img_names = []
# feature_matrices = []
# 
# for img_name in tqdm(image_name_train):
#     feature= extract_feature_from_image(img_name)
#     img_names.append(img_name)
#     feature_matrices.append(feature)
#     
# feature_dict= {'names': img_names, "features": feature_matrices}
# dump(feature_dict, open('./data/8kfeatures_dict.pkl','w'))

  0%|          | 0/8848 [00:00<?, ?it/s]

W1006 19:30:58.144114 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



W1006 19:30:58.160225 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W1006 19:30:58.162678 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W1006 19:30:58.173704 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



W1006 19:30:58.174005 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W1006 19:30:59.609845 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.



W1006 19:30:59.720405 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W1006 19:31:00.089112 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.



  0%|          | 1/8848 [00:10<25:57:11, 10.56s/it]

  0%|          | 2/8848 [00:19<24:36:22, 10.01s/it]

  0%|          | 3/8848 [00:29<24:22:35,  9.92s/it]

  0%|          | 4/8848 [00:40<25:21:28, 10.32s/it]

  0%|          | 5/8848 [00:52<27:04:28, 11.02s/it]

  0%|          | 6/8848 [01:07<29:29:22, 12.01s/it]

  0%|          | 7/8848 [01:23<32:24:05, 13.19s/it]

  0%|          | 8/8848 [01:40<35:09:34, 14.32s/it]

  0%|          | 9/8848 [01:59<38:59:39, 15.88s/it]

  0%|          | 10/8848 [02:20<42:19:12, 17.24s/it]

  0%|          | 11/8848 [02:42<46:30:41, 18.95s/it]

  0%|          | 12/8848 [03:06<49:53:10, 20.32s/it]

  0%|          | 13/8848 [03:32<54:02:19, 22.02s/it]

  0%|          | 14/8848 [03:58<57:16:20, 23.34s/it]

  0%|          | 15/8848 [04:26<60:37:32, 24.71s/it]

  0%|          | 16/8848 [04:57<65:03:52, 26.52s/it]

  0%|          | 17/8848 [05:28<68:20:08, 27.86s/it]

  0%|          | 18/8848 [06:01<71:50:13, 29.29s/it]

  0%|          | 19/8848 [06:35<75:20:26, 30.72s/it]

  0%|          | 20/8848 [07:12<80:17:46, 32.74s/it]

  0%|          | 21/8848 [07:50<83:46:43, 34.17s/it]

  0%|          | 22/8848 [08:29<87:23:02, 35.64s/it]

  0%|          | 23/8848 [09:09<90:57:13, 37.10s/it]

  0%|          | 24/8848 [09:51<94:35:33, 38.59s/it]

  0%|          | 25/8848 [10:37<99:54:45, 40.77s/it]

  0%|          | 26/8848 [11:23<103:15:42, 42.14s/it]

  0%|          | 27/8848 [12:10<106:47:44, 43.59s/it]

  0%|          | 28/8848 [12:58<110:21:28, 45.04s/it]

  0%|          | 29/8848 [13:48<113:58:51, 46.53s/it]

  0%|          | 30/8848 [14:39<117:35:14, 48.01s/it]

  0%|          | 31/8848 [15:35<123:01:44, 50.23s/it]

  0%|          | 32/8848 [16:29<126:06:05, 51.49s/it]

  0%|          | 33/8848 [17:25<129:31:30, 52.90s/it]

  0%|          | 34/8848 [18:23<133:05:34, 54.36s/it]

  0%|          | 35/8848 [19:23<136:47:13, 55.88s/it]

  0%|          | 36/8848 [20:24<140:33:04, 57.42s/it]

  0%|          | 37/8848 [21:26<144:20:09, 58.97s/it]

  0%|          | 38/8848 [22:30<148:01:30, 60.49s/it]

  0%|          | 39/8848 [23:39<153:54:33, 62.90s/it]

  0%|          | 40/8848 [24:46<157:01:53, 64.18s/it]

  0%|          | 41/8848 [25:55<160:23:10, 65.56s/it]

  0%|          | 42/8848 [27:05<163:43:09, 66.93s/it]

  0%|          | 43/8848 [28:17<167:21:19, 68.42s/it]

  0%|          | 44/8848 [29:30<171:12:49, 70.01s/it]

  1%|          | 45/8848 [30:46<175:07:03, 71.61s/it]

  1%|          | 46/8848 [32:03<178:59:52, 73.21s/it]

  1%|          | 47/8848 [33:21<182:48:52, 74.78s/it]

  1%|          | 48/8848 [34:45<189:33:53, 77.55s/it]

  1%|          | 49/8848 [36:07<192:33:59, 78.79s/it]

  1%|          | 50/8848 [37:30<195:44:52, 80.10s/it]

  1%|          | 51/8848 [38:55<199:21:20, 81.58s/it]

  1%|          | 52/8848 [40:22<202:56:54, 83.06s/it]

  1%|          | 53/8848 [41:50<206:27:31, 84.51s/it]

  1%|          | 54/8848 [43:19<210:14:20, 86.07s/it]

  1%|          | 55/8848 [44:51<214:03:42, 87.64s/it]

  1%|          | 56/8848 [46:23<217:37:13, 89.11s/it]

  1%|          | 57/8848 [47:57<221:11:28, 90.58s/it]

  1%|          | 58/8848 [49:33<225:02:52, 92.17s/it]

  1%|          | 59/8848 [51:10<228:51:09, 93.74s/it]

  1%|          | 60/8848 [52:54<236:02:43, 96.70s/it]

  1%|          | 61/8848 [54:35<238:55:46, 97.89s/it]

  1%|          | 62/8848 [56:17<242:00:48, 99.16s/it]

  1%|          | 63/8848 [57:59<244:05:23, 100.03s/it]

  1%|          | 64/8848 [59:44<248:04:05, 101.67s/it]

KeyboardInterrupt: 

In [14]:
# feature_dict= preprocess_img(image_name_train)
# dump(feature_dict, open('./data/8kfeatures_dict.pkl','w'))

  0%|          | 0/8848 [00:00<?, ?it/s]

W1006 16:06:09.995707 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



W1006 16:06:10.006417 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W1006 16:06:10.008131 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W1006 16:06:10.017329 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



W1006 16:06:10.017694 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W1006 16:06:10.589193 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.



W1006 16:06:10.704837 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W1006 16:06:11.114010 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.



  0%|          | 1/8848 [00:09<22:44:23,  9.25s/it]

  0%|          | 2/8848 [00:18<22:26:58,  9.14s/it]

  0%|          | 3/8848 [00:27<22:53:45,  9.32s/it]

  0%|          | 4/8848 [00:39<24:32:15,  9.99s/it]

  0%|          | 5/8848 [00:52<26:33:13, 10.81s/it]

  0%|          | 6/8848 [01:05<28:43:35, 11.70s/it]

  0%|          | 7/8848 [01:21<31:49:23, 12.96s/it]

  0%|          | 8/8848 [01:39<35:10:00, 14.32s/it]

  0%|          | 9/8848 [01:57<38:15:23, 15.58s/it]

  0%|          | 10/8848 [02:18<42:10:54, 17.18s/it]

  0%|          | 11/8848 [02:40<45:34:09, 18.56s/it]

  0%|          | 12/8848 [03:04<49:45:24, 20.27s/it]

  0%|          | 13/8848 [03:29<53:09:50, 21.66s/it]

  0%|          | 14/8848 [03:56<56:37:33, 23.08s/it]

  0%|          | 15/8848 [04:25<61:05:28, 24.90s/it]

  0%|          | 16/8848 [04:54<64:37:39, 26.34s/it]

  0%|          | 17/8848 [05:26<68:08:06, 27.78s/it]

  0%|          | 18/8848 [05:58<71:34:51, 29.18s/it]

  0%|          | 19/8848 [06:34<76:12:09, 31.07s/it]

  0%|          | 20/8848 [07:09<79:27:12, 32.40s/it]

  0%|          | 21/8848 [07:46<83:04:51, 33.88s/it]

  0%|          | 22/8848 [08:26<87:00:21, 35.49s/it]

  0%|          | 23/8848 [09:06<90:20:36, 36.85s/it]

  0%|          | 24/8848 [09:48<94:44:07, 38.65s/it]

  0%|          | 25/8848 [10:32<98:11:03, 40.06s/it]

  0%|          | 26/8848 [11:17<102:10:58, 41.70s/it]

  0%|          | 27/8848 [12:04<106:03:48, 43.29s/it]

  0%|          | 28/8848 [12:53<109:44:32, 44.79s/it]

  0%|          | 29/8848 [13:45<115:17:56, 47.07s/it]

  0%|          | 30/8848 [14:36<118:25:58, 48.35s/it]

  0%|          | 31/8848 [15:29<121:52:50, 49.76s/it]

  0%|          | 32/8848 [16:24<125:15:40, 51.15s/it]

  0%|          | 33/8848 [17:20<128:49:13, 52.61s/it]

  0%|          | 34/8848 [18:17<132:24:25, 54.08s/it]

  0%|          | 35/8848 [19:17<136:16:27, 55.67s/it]

  0%|          | 36/8848 [20:20<142:08:22, 58.07s/it]

  0%|          | 37/8848 [21:22<144:28:13, 59.03s/it]

  0%|          | 38/8848 [22:25<147:40:50, 60.35s/it]

  0%|          | 39/8848 [23:31<151:38:57, 61.97s/it]

  0%|          | 40/8848 [24:37<154:59:15, 63.35s/it]

  0%|          | 41/8848 [25:45<158:27:48, 64.77s/it]

  0%|          | 42/8848 [26:56<162:27:58, 66.42s/it]

  0%|          | 43/8848 [28:07<165:54:53, 67.84s/it]

  0%|          | 44/8848 [29:20<169:31:23, 69.32s/it]

  1%|          | 45/8848 [30:35<174:11:00, 71.23s/it]

  1%|          | 46/8848 [31:51<177:29:33, 72.59s/it]

  1%|          | 47/8848 [33:08<180:53:57, 74.00s/it]

  1%|          | 48/8848 [34:28<184:41:59, 75.56s/it]

  1%|          | 49/8848 [35:49<189:06:14, 77.37s/it]

  1%|          | 50/8848 [37:12<192:58:05, 78.96s/it]

  1%|          | 51/8848 [38:36<197:00:10, 80.62s/it]

  1%|          | 52/8848 [40:03<201:32:07, 82.48s/it]

  1%|          | 53/8848 [41:31<205:07:12, 83.96s/it]

  1%|          | 54/8848 [43:00<209:12:33, 85.64s/it]

  1%|          | 55/8848 [44:32<213:37:13, 87.46s/it]

  1%|          | 56/8848 [46:08<220:12:54, 90.17s/it]

  1%|          | 57/8848 [47:43<223:12:27, 91.41s/it]

  1%|          | 58/8848 [49:18<226:16:54, 92.68s/it]

  1%|          | 59/8848 [50:55<229:31:35, 94.01s/it]

  1%|          | 60/8848 [52:34<232:44:54, 95.35s/it]

  1%|          | 61/8848 [54:14<236:23:12, 96.85s/it]

  1%|          | 62/8848 [55:56<239:50:18, 98.27s/it]

  1%|          | 63/8848 [57:40<243:47:41, 99.90s/it]

  1%|          | 64/8848 [59:25<247:50:30, 101.57s/it]

  1%|          | 65/8848 [1:01:12<251:30:51, 103.09s/it]

  1%|          | 66/8848 [1:02:59<254:56:27, 104.51s/it]

  1%|          | 67/8848 [1:04:48<257:56:13, 105.75s/it]

  1%|          | 68/8848 [1:06:38<260:48:27, 106.94s/it]

  1%|          | 69/8848 [1:08:31<265:28:46, 108.87s/it]

  1%|          | 70/8848 [1:10:32<273:54:18, 112.33s/it]

  1%|          | 71/8848 [1:12:28<276:32:11, 113.43s/it]

  1%|          | 72/8848 [1:14:26<279:51:53, 114.80s/it]

  1%|          | 73/8848 [1:16:25<283:02:11, 116.12s/it]

  1%|          | 74/8848 [1:18:26<286:38:28, 117.61s/it]

  1%|          | 75/8848 [1:20:28<289:54:01, 118.96s/it]

  1%|          | 76/8848 [1:22:33<294:01:19, 120.67s/it]

  1%|          | 77/8848 [1:24:38<297:24:08, 122.07s/it]

  1%|          | 78/8848 [1:26:45<300:58:52, 123.55s/it]

  1%|          | 79/8848 [1:28:54<305:03:38, 125.24s/it]

  1%|          | 80/8848 [1:31:05<309:17:31, 126.99s/it]

  1%|          | 81/8848 [1:33:18<313:17:49, 128.65s/it]

  1%|          | 82/8848 [1:35:31<316:42:36, 130.07s/it]

  1%|          | 83/8848 [1:37:46<320:29:25, 131.63s/it]

  1%|          | 84/8848 [1:40:03<324:03:32, 133.11s/it]

  1%|          | 85/8848 [1:42:21<327:42:15, 134.63s/it]

  1%|          | 86/8848 [1:44:47<336:10:08, 138.12s/it]

  1%|          | 87/8848 [1:47:08<338:05:44, 138.93s/it]

  1%|          | 88/8848 [1:49:30<340:25:08, 139.90s/it]

  1%|          | 89/8848 [1:51:55<344:03:37, 141.41s/it]

  1%|          | 90/8848 [1:54:22<347:32:04, 142.86s/it]

  1%|          | 91/8848 [1:56:51<351:59:04, 144.70s/it]

  1%|          | 92/8848 [1:59:20<355:39:18, 146.23s/it]

  1%|          | 93/8848 [2:01:52<359:47:23, 147.94s/it]

  1%|          | 94/8848 [2:04:23<361:29:43, 148.66s/it]

  1%|          | 95/8848 [2:06:56<364:52:51, 150.07s/it]

  1%|          | 96/8848 [2:09:32<369:26:20, 151.96s/it]

  1%|          | 97/8848 [2:12:11<374:20:31, 154.00s/it]

  1%|          | 98/8848 [2:14:52<378:59:38, 155.93s/it]

  1%|          | 99/8848 [2:17:29<380:01:02, 156.37s/it]

  1%|          | 100/8848 [2:20:08<382:02:27, 157.22s/it]

  1%|          | 101/8848 [2:22:49<384:17:47, 158.16s/it]

  1%|          | 102/8848 [2:25:35<390:19:42, 160.67s/it]

  1%|          | 103/8848 [2:28:23<395:26:33, 162.79s/it]

  1%|          | 104/8848 [2:31:09<397:56:47, 163.84s/it]

  1%|          | 105/8848 [2:33:58<401:48:43, 165.45s/it]

  1%|          | 106/8848 [2:36:52<407:27:59, 167.80s/it]

  1%|          | 107/8848 [2:39:59<421:44:09, 173.69s/it]

In [12]:
vocab_size=4500
top_k = vocab_size-1
tokenizer = keras.preprocessing.text.Tokenizer(num_words=top_k,
                                                  oov_token="<unk>",
                                                  filters='!"#$%&()*+.,-/:;=?@[\]^_`{|}~ ')
tokenizer.fit_on_texts(caption_train)
tokenizer.word_index['<pad>'] = 0
tokenizer.index_word[0] = '<pad>'


train_seqs = tokenizer.texts_to_sequences(caption_train)
cap_vector_train = keras.preprocessing.sequence.pad_sequences(train_seqs,dtype='int32', padding='post',truncating='post',maxlen=max_length+1,value=0)

print(train_seqs[0])
print(cap_vector_train[0])



[3, 2, 117, 6, 201, 32, 764, 835, 703, 4]
[  3   2 117   6 201  32 764 835 703   4   0   0   0   0   0   0   0   0
   0   0   0]


/home/yiyang/project/caption/caption/data/val2014/COCO_val2014_000000565230.jpg
<start> a plane sitting on the runway in a clear field during a beautiful sunset <end>
0


In [23]:
# print(caption_train[0].shape)

AttributeError: 'str' object has no attribute 'shape'

In [13]:
start=0
train_num=8000
generator_train= batch_generator(BATCH_SIZE,vocab_size,train_num,start,image_name_train,senti_train,cap_vector_train,)


In [14]:
start2=0
train_num2=800
generator_dev= batch_generator(BATCH_SIZE,vocab_size,train_num2,start2,image_name_train,senti_train,cap_vector_train,)


In [15]:
reg=1e-4
decay=0
lr=0.001
initial_epoch=0

NIC_model=model(vocab_size,max_length,reg)
# complete_model= keras.Model(image_model.input,NIC_model.output)
NIC_model.compile(loss='categorical_crossentropy', optimizer=keras.optimizers.Adam(lr = lr, decay=decay), metrics=['accuracy'])


W1008 17:36:09.359705 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



W1008 17:36:09.372804 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W1008 17:36:09.375040 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W1008 17:36:09.385707 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



W1008 17:36:09.386350 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W1008 17:36:09.983248 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.



W1008 17:36:10.099091 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W1008 17:36:10.486855 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.



W1008 17:36:20.326653 139620787283776 deprecation.py:506] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


W1008 17:36:20.860184 139620787283776 deprecation.py:323] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:2974: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


W1008 17:36:20.895068 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



In [42]:
NIC_model.load_weights("models/NIC_model6.h5")
NIC_model.fit_generator(generator_train, steps_per_epoch=8000//BATCH_SIZE,
                        epochs=20,
                        verbose=2, 
                        validation_data=generator_dev,
                        validation_steps=100,
                        initial_epoch = 0)
NIC_model.save_weights("models/NIC_model6.h5")

Epoch 1/20


 - 93s - loss: 1.6621 - acc: 0.7933 - val_loss: 1.9323 - val_acc: 0.7201


Epoch 2/20


 - 87s - loss: 1.6515 - acc: 0.7961 - val_loss: 1.8942 - val_acc: 0.7292


Epoch 3/20


 - 87s - loss: 1.6499 - acc: 0.7968 - val_loss: 1.8851 - val_acc: 0.7348


Epoch 4/20


 - 87s - loss: 1.6479 - acc: 0.7969 - val_loss: 1.8511 - val_acc: 0.7360


Epoch 5/20


 - 87s - loss: 1.6483 - acc: 0.7953 - val_loss: 1.9197 - val_acc: 0.7268


Epoch 6/20


 - 87s - loss: 1.6428 - acc: 0.7988 - val_loss: 1.8870 - val_acc: 0.7317


Epoch 7/20


 - 87s - loss: 1.6479 - acc: 0.7966 - val_loss: 1.9192 - val_acc: 0.7256


Epoch 8/20


 - 88s - loss: 1.6439 - acc: 0.7982 - val_loss: 1.8965 - val_acc: 0.7316


Epoch 9/20


 - 88s - loss: 1.6443 - acc: 0.7964 - val_loss: 1.9181 - val_acc: 0.7260


Epoch 10/20


 - 88s - loss: 1.6403 - acc: 0.7986 - val_loss: 1.8362 - val_acc: 0.7448


Epoch 11/20


 - 87s - loss: 1.6398 - acc: 0.7983 - val_loss: 1.8784 - val_acc: 0.7351


Epoch 12/20


 - 87s - loss: 1.6372 - acc: 0.7999 - val_loss: 1.9072 - val_acc: 0.7316


Epoch 13/20


 - 87s - loss: 1.6395 - acc: 0.7996 - val_loss: 1.8775 - val_acc: 0.7370


Epoch 14/20


 - 87s - loss: 1.6293 - acc: 0.8026 - val_loss: 1.8951 - val_acc: 0.7320


Epoch 15/20


 - 87s - loss: 1.6342 - acc: 0.8004 - val_loss: 1.9134 - val_acc: 0.7225


Epoch 16/20


 - 87s - loss: 1.6337 - acc: 0.8010 - val_loss: 1.9121 - val_acc: 0.7262


Epoch 17/20


 - 89s - loss: 1.6317 - acc: 0.8009 - val_loss: 1.8912 - val_acc: 0.7331


Epoch 18/20


 - 88s - loss: 1.6333 - acc: 0.8006 - val_loss: 1.8726 - val_acc: 0.7358


Epoch 19/20


 - 88s - loss: 1.6330 - acc: 0.8003 - val_loss: 1.9029 - val_acc: 0.7290


Epoch 20/20


 - 87s - loss: 1.6287 - acc: 0.8012 - val_loss: 1.8936 - val_acc: 0.7307


In [43]:

NIC_inference = greedy_inference_model(vocab_size, max_length)
NIC_inference.load_weights("models/NIC_model6.h5", by_name = True, skip_mismatch=True)

In [54]:
test_imgs=[]
num_test=500
start=8000
for j in tqdm(range(start,start+num_test)):
    img= load_image( image_name_train[j])
    test_imgs.append(img)
test_imgs= np.array(test_imgs)
test_sentis= np.array(senti_train[start:start+num_test])
test_sequences= np.array(cap_vector_train[start:start+num_test])
# test_seq= np.ones(shape=(500,1))
# test_seq= 3* test_seq
# test_out=[]


  0%|          | 0/500 [00:00<?, ?it/s]

  3%|▎         | 17/500 [00:00<00:02, 166.72it/s]

  7%|▋         | 35/500 [00:00<00:02, 170.42it/s]

 11%|█         | 55/500 [00:00<00:02, 176.30it/s]

 14%|█▍        | 71/500 [00:00<00:02, 170.13it/s]

 18%|█▊        | 89/500 [00:00<00:02, 171.80it/s]

 22%|██▏       | 109/500 [00:00<00:02, 177.33it/s]

 26%|██▌       | 130/500 [00:00<00:02, 184.68it/s]

 30%|██▉       | 149/500 [00:00<00:01, 185.20it/s]

 34%|███▍      | 169/500 [00:00<00:01, 188.36it/s]

 38%|███▊      | 189/500 [00:01<00:01, 190.07it/s]

 42%|████▏     | 211/500 [00:01<00:01, 197.06it/s]

 46%|████▌     | 231/500 [00:01<00:01, 190.42it/s]

 50%|█████     | 251/500 [00:01<00:01, 190.60it/s]

 54%|█████▍    | 270/500 [00:01<00:01, 190.29it/s]

 58%|█████▊    | 292/500 [00:01<00:01, 197.81it/s]

 63%|██████▎   | 313/500 [00:01<00:00, 199.10it/s]

 67%|██████▋   | 335/500 [00:01<00:00, 204.10it/s]

 71%|███████   | 356/500 [00:01<00:00, 196.78it/s]

 75%|███████▌  | 376/500 [00:01<00:00, 194.87it/s]

 79%|███████▉  | 396/500 [00:02<00:00, 194.11it/s]

 83%|████████▎ | 416/500 [00:02<00:00, 195.25it/s]

 87%|████████▋ | 436/500 [00:02<00:00, 189.34it/s]

 92%|█████████▏| 458/500 [00:02<00:00, 195.62it/s]

 96%|█████████▌| 478/500 [00:02<00:00, 195.71it/s]

100%|█████████▉| 499/500 [00:02<00:00, 199.23it/s]

100%|██████████| 500/500 [00:02<00:00, 192.12it/s]

In [63]:
N = test_imgs.shape[0]

startseq = np.repeat([tokenizer.word_index['<start>']], N)
a0 = np.zeros([N, units])
c0 = np.zeros([N, units])
# test_sentis= np.ones([500])
# test_sentis= - np.ones([500])
test_sentis= np.zeros([500])
# output dims: [32, N, 7378]
y_preds = np.array(NIC_inference.predict([test_imgs, startseq,test_sentis, a0, c0], verbose = 1))

# output dims: [N, 32, 7378]
y_preds = np.transpose(y_preds, axes = [1,0,2])

sequences = np.argmax(y_preds, axis = -1)
sents = tokenizer.sequences_to_texts(sequences)

# if post_process:
    # post processing: 'endseq'
sents_pp = []
for sent in sents:
    if '<end>' in sent.split():
        words = sent.split()
        sents_pp.append(' '.join(words[:words.index('<end>')]))
    else:
        sents_pp.append(sent)
sents = sents_pp


 32/500 [>.............................] - ETA: 2s

 64/500 [==>...........................] - ETA: 1s

 96/500 [====>.........................] - ETA: 1s

128/500 [======>.......................] - ETA: 1s

160/500 [========>.....................] - ETA: 1s

192/500 [==========>...................] - ETA: 1s

224/500 [============>.................] - ETA: 0s

256/500 [==============>...............] - ETA: 0s

288/500 [================>.............] - ETA: 0s

320/500 [==================>...........] - ETA: 0s

352/500 [====================>.........] - ETA: 0s

384/500 [======================>.......] - ETA: 0s

416/500 [=======================>......] - ETA: 0s

448/500 [=========================>....] - ETA: 0s

480/500 [===========================>..] - ETA: 0s

500/500 [==============================] - 2s 3ms/step


In [64]:
print(sents[400:])

['a dead man is flying a kite on the beach', 'a plate of different plates of sandwiches at a good restaurant', 'a plate of different plates of sandwiches at a good restaurant', 'a plate of different plates of sandwiches at a good restaurant', 'a group of wine glasses sit on a nice glass bar', 'a group of wine glasses sit on a nice glass bar', 'a group of wine glasses sit on a nice glass bar', 'a train traveling on some train tracks in front of an abandoned building', 'a train traveling on some train tracks in front of an abandoned building', 'a train traveling on some train tracks in front of an abandoned building', 'a man playing frisbee in a beautiful park', 'a man playing frisbee in a beautiful park', 'a man playing frisbee in a beautiful park', 'a man and a woman eating tasty food at a table', 'a man and a woman eating tasty food at a table', 'a man and a woman eating tasty food at a table', 'a dead man standing on top of a frisbee in the water', 'a dead man standing on top of a fr

In [66]:
# f1='output/gen_data.json'
# f2='output/gen_data.txt'
gen_data={}
gen_data['annotations']=[]
ref_data={}
ref_data['annotations']=[]
start=0
for i in trange(500):
    img_id= image_vec[start+i]
    gen_cap= sents[i]
    ref_cap= caption_train[start+i]
    ref_cap= ref_cap.replace("<start>","")
    ref_cap= ref_cap.replace("<end>","")
    ref_cap= ref_cap.strip()
    ref_cap= "".join(ref_cap)
    gen_data['annotations'].append({'image_id':img_id,'caption':gen_cap})
    
    ref_data['annotations'].append({'image_id':img_id,'caption':ref_cap})
    
with open("output/gen_data.json", "w") as f2:
    json.dump(gen_data, f2)
    
with open("output/ref_data.json", "w") as f3:
    json.dump(ref_data, f3)

with open("output/gen_data_neu.txt","w") as f4:
    for item in gen_data["annotations"]:
        cap= item['caption']
        f4.write("%s .\n" % cap)

  0%|          | 0/500 [00:00<?, ?it/s]

100%|██████████| 500/500 [00:00<00:00, 241273.82it/s]

In [21]:
test= caption_train[start:start+2]
for element in test:
    temp= element.replace("<start>","")
    temp= temp.replace("<end>","")
    print("#"+temp+"#")
# print(test)
# print(sents[:10])

# a plane sitting on the runway in a clear field during a beautiful sunset #
# a plane sitting on the runway with an amazing sunset #


In [19]:
base_model = InceptionV3(include_top=True, weights=None)
weights_path = 'data/image_net.h5'
# image_model = tf.keras.applications.InceptionV3(include_top=False,
#                                                 weights='imagenet')
base_model.load_weights(weights_path)
# print(base_model.output_shape)
for layer in base_model.layers[:312]:
    layer.trainable = False

new_input = base_model.layers[0].input
hidden_layer = base_model.get_layer('avg_pool').output

image_model = Model(new_input, hidden_layer)

    

W1005 22:46:31.953823 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



W1005 22:46:31.967643 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W1005 22:46:31.969490 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W1005 22:46:31.979786 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



W1005 22:46:31.980213 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W1005 22:46:32.558979 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.



W1005 22:46:32.663625 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W1005 22:46:32.962079 139620787283776 deprecation_wrapper.py:119] From /home/yiyang/anaconda3/envs/caption/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3980: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.



In [22]:

img_num=8003
 
print(image_vec[img_num])
# img=load_image(image_name_train[0])
img=cv2.imread(image_vec[img_num]) 
print(caption_vec[img_num])
print(sentiment_vec[img_num])
# img=cv2.imshow('image',img)
cv2.imshow('ImageWindow', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

 

/home/yiyang/project/caption/caption/data/val2014/COCO_val2014_000000184606.jpg
<start> a funny dog paddling through some calm water in front of a building <end>
1


In [ ]:

print(img_out)